class HDPromptEngine:
    """Advanced prompt alignment layer for precise audio-to-audio replication matching."""

    @staticmethod
    def construct_meta_tags(dna_metrics: dict) -> str:
        """Compiles standard production descriptors and detailed vocal textures into clean machine prompts."""
        return (
            f"{dna_metrics['detected_genre']}, Tempo matched to {dna_metrics['bpm']} BPM, "
            f"Key signature profile: {dna_metrics['estimated_key']}, Vocal Setup: {dna_metrics['vocal_timbre']}, "
            f"Arrangement Matrix: {dna_metrics['instruments']}, 80s synth hooks, punchy retro electronic snare, "
            f"heavy wall of vocal harmony, crisp commercial mix, analog tape saturation warmth, 44.1kHz master tracking"
        )

    @staticmethod
    def generate_exact_lyric_sheet() -> str:
        """Produces the exact structural lyric blueprint matching the user's recorded audio track file profile."""
        return (
            "[Instrumental Intro]\n"
            "[Driving electronic beat, pulsing synth bass rhythm, ambient electric guitar textures]\n\n"
            "[Verse 1]\n"
            "(Female Lead Voice, pure and strong)\n"
            "You walked in tall, smoke and shine\n"
            "Kept your name above of mine\n"
            "Every word came sharp like glass\n"
            "Cut the room and let it pass\n\n"
            "[Pre-Chorus]\n"
            "(Female Lead with subtle low male baritone harmony underlying)\n"
            "You wanted wins, you wanted praise\n"
            "Wanted all eyes on you for days\n"
            "But the ones who stood real close\n"
            "Felt that heat then felt you go\n\n"
            "[Chorus]\n"
            "(Main Female Lead explodes with a massive multi-voice choral backing group, heavy echoing)\n"
            "Now the tables have along\n"
            "Now the air feels cold and wrong\n"
            "You said I'm fine, I'm fine\n"
            "But the line kept breaking in time\n"
            "Pride and ego!\n"
            "Pride and ego!\n"
            "You built that wall so high\n"
            "Now you're standing on the wrong side\n"
            "Pride and ego!\n"
            "Pride and ego!\n"
            "You pushed them all away\n"
            "Now there's no one left to stay\n"
            "(Choral Backing Group Echoes): No one left to stay...\n"
            "No one left to stay\n"
            "(Choral Backing Group Echoes): No one left to stay...\n\n"
            "[Verse 2]\n"
            "(Female Lead Voice, pure and clear)\n"
            "It wasn't one big final fight\n"
            "It was a thousand small goodbye nights\n"
            "Little cuts you never saw\n"
            "Till the silence hit the floor\n\n"
            "[Pre-Chorus]\n"
            "(Female Lead with subtle low male backing harmonies)\n"
            "You kept score, you kept the crown\n"
            "Kept talking louder than the sound\n"
            "But every hand you tried to hold\n"
            "Pulled back slow and let you go\n\n"
            "[Chorus]\n"
            "(Full massive multi-voice group chorus, explosive delivery)\n"
            "Now the tables have along\n"
            "Now the air feels cold and wrong\n"
            "You said I'm fine, I'm fine\n"
            "But the line kept breaking in time\n"
            "Pride and ego!\n"
            "Pride and ego!\n"
            "You built that wall so high\n"
            "Now you're standing on the wrong side\n"
            "Pride and ego!\n"
            "Pride and ego!\n"
            "You pushed them all away\n"
            "Now there's no one left to stay\n"
            "(Choral Backing Group Echoes): No one left to stay...\n"
            "No one left to stay\n\n"
            "[Bridge]\n"
            "(Female Lead Voice dynamic shift, building instrumentation)\n"
            "Look at the space you made\n"
            "All the names that slipped away\n"
            "Was it worth the pride?\n"
            "Was it worth being alone?\n"
            "(Explosive build-up dynamic breakdown):\n"
            "Break it down!\n"
            "Let it fall!\n"
            "Say you're sorry!\n"
            "Mean it all!\n\n"
            "[Chorus]\n"
            "(Max energy, full vocal choir, soaring leads, screaming synths)\n"
            "Pride and ego!\n"
            "Pride and ego!\n"
            "You built that wall so high\n"
            "Now you're standing on the wrong side\n"
            "Pride and ego!\n"
            "Pride and ego!\n"
            "You pushed them all away\n"
            "Now there's no one left to stay\n\n"
            "[Outro]\n"
            "(Synth tracking patterns fade down, rhythm drum tracking exits)\n"
            "No one left to stay...\n"
            "[Fade to End]\n"
            "[End]"
        )
